# This is the wallet class file which is responsible to generate the public and private keys in the application.
# The system of public and private keys work in a way that every public key has a unique private key and it can not
# be changed once generated by the package which is installed "Cryptodome."
# Even if a hacker or intruder tries to modify the key they will be recieving their own new private key for the modified
# public key but the original public key is unaltered ensuring the safety in the system.
# So, public_key is public as the name suggests and it can be used as an identifier or as an user id to represent a user.
# Private_key is to be secured and should be stored safely to ensure authenticity of the user wallet.

# importing the crypto package.
from Crypto.PublicKey import RSA
import Crypto.Random

import binascii

class Wallet:
    def __init__(self):
        self.public_key = None
        self.private_key = None
    
    def create_keys(self):
        private_key, public_key = self.generate_keys()
        self.private_key = private_key
        self.public_key = public_key

    def load_keys(self):
        pass

    def generate_keys(self):
        private_key = RSA.generate(1024, Crypto.Random.new().read())
        public_key = private_key.public_key()
        return (
            binascii.hexlify(private_key.exportKey(format="DER")).decode(),
            binascii.hexlify(public_key.exportKey(format="DER")).decode(),
            )


