# This is the wallet class file which is responsible to generate the public and private keys in the application.
# The system of public and private keys work in a way that every public key has a unique private key and it can not
# be changed once generated by the package which is installed "Cryptodome."
# Even if a hacker or intruder tries to modify the key they will be recieving their own new private key for the modified
# public key but the original public key is unaltered ensuring the safety in the system.
# So, public_key is public as the name suggests and it can be used as an identifier or as an user id to represent a user.
# Private_key is to be secured and should be stored safely to ensure authenticity of the user wallet.

# importing the crypto package.
from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
from Crypto.Hash import SHA256
import Crypto.Random

import binascii

class Wallet:
    def __init__(self):
        self.public_key = None
        self.private_key = None
    
    def create_keys(self):
        private_key, public_key = self.generate_keys()
        self.private_key = private_key
        self.public_key = public_key


    def load_keys(self):
        try:
            with open('keys.txt',  mode='r') as f:
                private_key = f.readlines[0][:-1]
                public_key = f.readlines[1]
                self.private_key = private_key
                self.public_key = public_key
                return True
        except (IOError, IndexError):
            print('Loading Keys failes.')
            return False
        

    def save_keys(self):
        if self.public_key != None and self.private_key != None:
            try:
                with open('keys.txt', mode='w') as f:
                    f.write[self.private_key]
                    f.write('/n')
                    f.write(self.public_key)
                    return True
            except (IOError, IndexError):
                print('Saving Keys failed.')
                return False


    def generate_keys(self):
        private_key = RSA.generate(1024, Crypto.Random.new().read())
        public_key = private_key.public_key()
        return (
            binascii.hexlify(private_key.exportKey(format="DER")).decode(),
            binascii.hexlify(public_key.exportKey(format="DER")).decode(),
            )
    

    def sign_transactions(self, sender, recipient, amount):
        signer = PKCS1_v1_5.new(RSA.import_key(binascii.unhexlify(self.private_key)))
        h = SHA256.new((str(sender) + str(recipient) + str(amount)).encode('utf-8'))
        signature = signer.sign(h)
        return binascii.hexlify(signature).decode('ascii')
    

    @staticmethod
    def verify_transactions(transaction):
        public_key = RSA.import_key(binascii.unhexlify(transaction.sender))
        verifier = PKCS1_v1_5.new(public_key)
        h = SHA256.new((str(transaction.sender) + str(transaction.recipient) + str(transaction.amount)).encode('utf-8'))
        return verifier.verify(h, binascii.unhexlify(transaction.signature))


